# Generated by Django 5.1 on 2024-08-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedata',
            old_name='speaker_count',
            new_name='speaker',
        ),
    ]
