# Generated by Django 5.1 on 2024-08-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0003_gameinput_delete_gamedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinput',
            old_name='speaker_count',
            new_name='game_number',
        ),
    ]
